api_platform:
    title: Documentation Knowledge E-Learning 
    description: Plateforme d'apprentissage
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
