<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cursus extends \App\Entity\Cursus implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Name_cursus' => [parent::class, 'Name_cursus', null],
        "\0".parent::class."\0".'Price' => [parent::class, 'Price', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id_cursus' => [parent::class, 'id_cursus', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'lesson' => [parent::class, 'lesson', null],
        "\0".parent::class."\0".'theme' => [parent::class, 'theme', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'Name_cursus' => [parent::class, 'Name_cursus', null],
        'Price' => [parent::class, 'Price', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'id_cursus' => [parent::class, 'id_cursus', null],
        'images' => [parent::class, 'images', null],
        'lesson' => [parent::class, 'lesson', null],
        'theme' => [parent::class, 'theme', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
