<?php

namespace Container5Y7g603;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQxDvLO.App\Controller\CertificationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQxDvLO.App\\Controller\\CertificationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
            'themeRepository' => ['privates', 'App\\Repository\\ThemeRepository', 'getThemeRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
            'themeRepository' => 'App\\Repository\\ThemeRepository',
        ]))->withContext('App\\Controller\\CertificationController::index()', $container);
    }
}
