<?php

namespace Container5Y7g603;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControlleraddToCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V5uW.q5.App\Controller\CartController::addToCart()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.V5uW.q5'] ?? $container->load('get_ServiceLocator_V5uW_Q5Service'));

        if (isset($container->privates['.service_locator.V5uW.q5.App\\Controller\\CartController::addToCart()'])) {
            return $container->privates['.service_locator.V5uW.q5.App\\Controller\\CartController::addToCart()'];
        }

        return $container->privates['.service_locator.V5uW.q5.App\\Controller\\CartController::addToCart()'] = $a->withContext('App\\Controller\\CartController::addToCart()', $container);
    }
}
