<?php

namespace Container5Y7g603;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllercreateCheckoutSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.83UD8HJ.App\Controller\CheckoutController::createCheckoutSession()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.83UD8HJ.App\\Controller\\CheckoutController::createCheckoutSession()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'stripeService' => ['privates', 'App\\Service\\StripeService', 'getStripeServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'stripeService' => 'App\\Service\\StripeService',
            'em' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::createCheckoutSession()', $container);
    }
}
