<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lesson extends \App\Entity\Lesson implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Price' => [parent::class, 'Price', null],
        "\0".parent::class."\0".'certificationImage' => [parent::class, 'certificationImage', null],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'cursus' => [parent::class, 'cursus', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id_lesson' => [parent::class, 'id_lesson', null],
        "\0".parent::class."\0".'name_lesson' => [parent::class, 'name_lesson', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'video_url' => [parent::class, 'video_url', null],
        'Price' => [parent::class, 'Price', null],
        'certificationImage' => [parent::class, 'certificationImage', null],
        'content' => [parent::class, 'content', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'cursus' => [parent::class, 'cursus', null],
        'description' => [parent::class, 'description', null],
        'id_lesson' => [parent::class, 'id_lesson', null],
        'name_lesson' => [parent::class, 'name_lesson', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'video_url' => [parent::class, 'video_url', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
