<?php

namespace ContainerTW2juWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllersuccessPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.62ILKvH.App\Controller\CheckoutController::successPayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.62ILKvH.App\\Controller\\CheckoutController::successPayment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::successPayment()', $container);
    }
}
