<?php

namespace ContainerCayvFEX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Symfony_UriVariables_Transformer_UlidService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.symfony.uri_variables.transformer.ulid' shared service.
     *
     * @return \ApiPlatform\Symfony\UriVariableTransformer\UlidUriVariableTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'metadata'.\DIRECTORY_SEPARATOR.'UriVariableTransformerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'UriVariableTransformer'.\DIRECTORY_SEPARATOR.'UlidUriVariableTransformer.php';

        return $container->privates['api_platform.symfony.uri_variables.transformer.ulid'] = new \ApiPlatform\Symfony\UriVariableTransformer\UlidUriVariableTransformer();
    }
}
