<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCayvFEX\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCayvFEX/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCayvFEX.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCayvFEX\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCayvFEX\App_KernelTestDebugContainer([
    'container.build_hash' => 'CayvFEX',
    'container.build_id' => '5646bde8',
    'container.build_time' => 1738461963,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCayvFEX');
