<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Y7g603\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Y7g603/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Y7g603.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Y7g603\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5Y7g603\App_KernelDevDebugContainer([
    'container.build_hash' => '5Y7g603',
    'container.build_id' => 'b5097c2c',
    'container.build_time' => 1738377499,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Y7g603');
