<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTW2juWT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTW2juWT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTW2juWT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTW2juWT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTW2juWT\App_KernelDevDebugContainer([
    'container.build_hash' => 'TW2juWT',
    'container.build_id' => 'de89f292',
    'container.build_time' => 1738279637,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTW2juWT');
